name: tristapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_map: ^8.1.1
  flutter_svg: ^2.1.0
  flutter_svg_provider: ^1.0.7
  intl: ^0.20.2
  latlong2: ^0.9.1
  pocketbase: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets: 
  - assets/
  - secret_dont_look_at_me.env
